version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:2.16.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Hakuna@26112002"
      DISABLE_SECURITY_PLUGIN: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  springapi:
    image: springapi
    container_name: springapi
    ports:
      - 8080:8080
    environment:
      OPENSEARCH_MODE: http
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASS: Hakuna@26112002
      AWS_ACCESSKEY: AKIAXQY44YBJN73LN2UG
      AWS_SECRETKEY: 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
    volumes:
      - E:/Training_Dataset:/Dataset
    networks:
      - opensearch-net
    depends_on:
      - opensearch

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge